NEST-281: Ability to log in as a tenant’s admin user
Lombiq/Hosting-Tenants pull request #1
Opened 2021-09-01 13:16 UTC by Azaliusz

NEST-281

2021-09-01 18:21 UTC, Piedone requested changes

2021-09-01 18:21 UTC, Piedone commented on .gitignore
> +## Visual Studio temporary files, build results, and
Ez egy solution gitignore, de elég lesz egy modulos is.

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Lombiq.Hosting.Tenants.Admin.csproj
> +
Formázás nem oké.

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Manifest.cs
> +    Name = "Lombiq Hosting Tenants Admin",
```suggestion
    Name = "Lombiq Hosting - Tenants Admin",
```

A többi helyen is.

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Manifest.cs
> +    Name = "Lombiq Hosting Tenants - Subtenant",
"Sub-tenant" inkább.

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Views/TenantAdminShape.cshtml
> +            .FirstOrDefault();
Ez egy tabra van csak a `var` vonalától?

2021-09-01 18:21 UTC, Piedone commented on Readme.md
> +# Lombiq Hosting Tenants
```suggestion
# Lombiq Hosting - Tenants
```

Lásd még: https://github.com/Lombiq/Orchard-Azure-Application-Insights

2021-09-01 18:21 UTC, Piedone commented on Readme.md
> +Various libraries that help to build a multi-tenant web application in Orchard Core.
```suggestion
Various modules that help you build a multi-tenant web application in Orchard Core. 
```

2021-09-01 18:21 UTC, Piedone commented on Readme.md
>  ## Contributing and support
Formázási szabályokért lásd: https://lombiq.atlassian.net/wiki/spaces/DEV/pages/12156958/Adding+documentation+pages+to+our+projects Továbbá: https://lombiq.atlassian.net/wiki/spaces/DEV/pages/10453016/Documenting+our+projects

```suggestion


## Contributing and support
```

2021-09-01 18:21 UTC, Piedone commented on Readme.md
> +The module consists of the following independent libraries (all in their own features):
```suggestion
The project consists of the following independent modules:
```

2021-09-01 18:21 UTC, Piedone commented on Readme.md
> +- [Lombiq Hosting Tenants - Admin](Lombiq.Hosting.Tenants.Admin/Readme.md)
```suggestion
The module consists of the following independent libraries (all in their own features):

- [Lombiq Hosting Tenants - Admin](Lombiq.Hosting.Tenants.Admin/Readme.md)
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +## About
```suggestion
# Lombiq Hosting Tenants - Admin



## About
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +With the help of this module, you can log in from the Default tenant admin dashboard to any other tenants as an administrator user.
```suggestion
With the help of this module, you can log in from the Default tenant's admin dashboard to any other tenants as an administrator user. This is useful if you manage a lot of customer tenants and don't want to create individual logins of yours for each of them.
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +- Lombiq.Hosting.Tenants.Admin
Mivel ez egy technical name, így kellene formázni, meg a másik feature-t is, az összes többi helyen is, címekben is.

```suggestion
- `Lombiq.Hosting.Tenants.Admin`
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +This feature is only available on the Default tenant. It provides a button on the tenant edit page. After clicking this button the site login to the selected tenant as an administrator and redirect t
```suggestion
This feature is only available on the Default tenant. It provides a button on the tenant editor page. After clicking this button, you'll be logged to the selected tenant as an administrator and be redirected to its admin dashboard. 
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +**_NOTE:_**  Login will not be successful if the tenant has no user with administrator role
```suggestion
**NOTE:**  Login will not be successful if the tenant has no user with the administrator role.
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +The feature also provides a LoginAsAdmin permission. Only the user who has this permission can see the login button.
```suggestion
The feature also provides a `LoginAsAdmin` permission. Only users who have this permission can see the login button (by default users possessing the Administrator role).
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +This feature is only available on the Default tenant. It provides a button on the tenant edit page. After clicking this button the site login to the selected tenant as an administrator and redirect t
Ezután rakj be egy screenshotot a buttonnal légyszi. Ez egy "Demo" nevű új tenant legyen hasonlóan dummy részletekkel. Elég, ha csak a tenant editor látszik. Szal a cél az, hogy a user megértse, hol keresse a buttont.

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +This feature provides a controller which can authenticate the request from the Default tenant as an administrator user. From the Default tenant, you can log in to only those tenants in which this fea
```suggestion
This feature provides a controller which can authenticate the request from the Default tenant as an administrator user. From the Default tenant, you can log in to only those tenants that have this feature enabled.
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +## How to enable SubTenant feature on every tenants
```suggestion
## How to enable the Sub-tenant feature on every tenant
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +                });
```suggestion
public void ConfigureServices(IServiceCollection services) =>
    services.AddOrchardCms(
        builder => builder.AddTenantFeatures(Lombiq.Hosting.Tenants.Admin.Constants.FeatureNames.SubTenant));
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +**_NOTE:_**  This way the feature will also be enabled in the Default tenant. Therefore, for greater security, the controller does not perform authentication on the Default tenant.
```suggestion
**NOTE:**  This way the feature will also be enabled on the Default tenant. Therefore, for greater security, the controller does not perform anything on the Default tenant.
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +- [Lombiq-Helpful-Libraries](https://github.com/Lombiq/Helpful-Libraries)
```suggestion
- [Lombiq Helpful Libraries for Orchard Core](https://github.com/Lombiq/Helpful-Libraries)
```

2021-09-01 18:21 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Controllers/TenantLoginController.cs
> +                _shellSettings.Name.EqualsOrdinalIgnoreCase(ShellHelper.DefaultShellName) ||
Ez a check lehetne az első sorban külön, szóval, hogy a többi az `IShellHost`-tal le se fussson.

2021-09-02 07:27 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Admin/Views/TenantAdminShape.cshtml
> +            .FirstOrDefault();
4 spacre van a `var`-tól. Mennyivel kéne még beljebb tolni ?

2021-09-02 14:46 UTC, Piedone commented on .gitignore
> +.vs/
Ez szerintem csak solutionben érdekes. Amúgy a fájl végi sortörés maradjon (ezt mutatja itt a diffben behajtani tilos táblaként a GH).

2021-09-02 14:46 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Lombiq.Hosting.Tenants.Admin.csproj
> +  <ItemGroup>
Ez már jó, de ha itt a diffet megnézed, akkor még mindig inkonzisztens a formázás, ezért:
![image](https://user-images.githubusercontent.com/1976647/131864630-41c20649-b0c4-447a-b58a-34e990ad3850.png)

2021-09-02 14:46 UTC, Piedone commented on Readme.md
> +Various libraries that help to build a multi-tenant web application in Orchard Core.
Amúgy ezeket be tudod egyből commitolni innen is, és akkor auto-resolve-olódik, ami jó.

2021-09-02 14:51 UTC, Piedone requested changes

2021-09-02 14:51 UTC, Piedone commented on Lombiq.Hosting.Tenants.Admin/Readme.md
> +![Tenant's editor page with Login as admin user button.](Docs/Attachments/Tenant'sEditorPageWithLoginAsAdminUserButton.png)
Aposztróf ne legyen fájlnevekben légyszi, mert mindenféle vicces problémákat tud okozni.

2021-09-02 15:07 UTC, Azaliusz commented on .gitignore
> +.vs/
"szerintem csak solutionben érdekes" melyikre vonatkozik? a .vs re vagy a teljes .gitignore-ra? 
Ez a mostani .gitignore a `Lombiq.TrainingDemo`-bol van inkább használjam a [Helpful-Libraries](https://github.com/Lombiq/Helpful-Libraries/blob/dev/.gitignore) repó root gitignore-ját?

2021-09-02 15:11 UTC, Piedone commented on .gitignore
> +.vs/
A .vs-re. Ugye az ilyen commenteknél látod, hogy mire commenteltem, és ez csak az adott sorra van. A többi maradjon.

2021-09-03 14:27 UTC, merged