NEST-283: Prevent recipes with the “developer” category to be listed on the setup screen
Lombiq/Hosting-Tenants pull request #5
Opened 2021-10-20 12:28 UTC by Azaliusz

[NEST-283](https://lombiq.atlassian.net/browse/NEST-283)

2021-10-20 20:09 UTC, Piedone requested changes

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Constants/FeatureNames.cs
> +        public const string ForbindenTenantNames = Module + "." + nameof(ForbindenTenantNames);
Ez a typo több helyen is előjön.

```suggestion
        public const string ForbiddenTenantNames = Module + "." + nameof(ForbiddenTenantNames);
```

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +        public static OrchardCoreBuilder HideRecipesByCategoryFromSetup(this OrchardCoreBuilder builder, params string[] categories) =>
Ne haragudj, inkább ez is menjen tagekkel, mint a `hidden` tag. Így jobban illik a beépített feature-höz.

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +        public static OrchardCoreBuilder HideRecipesByCategoryFromSetup(this OrchardCoreBuilder builder, params string[] categories) =>
Doc legyen rajta.

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Manifest.cs
> +    Description = "Ability to configure hostnames that don't allow during tenant creation.",
```suggestion
    Description = "Ability to configure hostnames that aren't allowed during tenant creation.",
```

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Manifest.cs
> +    Description = "Ability to configure recipe categories witch won't be available during tenant setup.",
```suggestion
    Description = "Ability to configure recipe tags that won't be available during tenant setup.",
```

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Lombiq.Hosting.Tenants.Management.csproj
> +    <PackageReference Include="OrchardCore.AutoSetup" Version="1.0.0" />
Biztos AutoSetup reference kell, nem Setup?

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Readme.md
> +You can specify the recipe categories you want to hide using the `HideRecipesByCategoryFromSetup()` function in the web project `ConfigureServices()`.
```suggestion
With this module, you can specify tags for recipes that won't be listed on the setup screen of tenants. Recipes with those tags will still be available from the Default tenant admin UI and they'll also be available to be used via the `AutoSetup` feature.

You can specify the recipe categories you want to hide using the `HideRecipesByCategoryFromSetup()` method in the web project's `ConfigureServices()`.
```

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Readme.md
> +  services.AddOrchardCms(builder=>builder.HideRecipesByCategoryFromSetup("hiddenCategory1","hiddenCategory2"))
```suggestion
public void ConfigureServices(IServiceCollection services) =>
    services.AddOrchardCms(builder => builder.HideRecipesByCategoryFromSetup("hiddenCategory1", "hiddenCategory2"))
```

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +                        settings.HiddenCategories = new List<string>(categories)));
Miért szükséges a Listbe másolás?

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Service/SetupWithRecipesFilterService.cs
> +#pragma warning disable S107 // Methods should not have too many parameters
Commenteld a suppress okát.

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Service/SetupWithRecipesFilterService.cs
> +            _setupService = new(
Kézi decorator helyett használhatnád a már bevált Scrutort: https://github.com/khellang/Scrutor

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Service/SetupWithRecipesFilterService.cs
> +                => tenant.ShellName == _shellSettings.Name);
```suggestion
            var currentTenantSetupOptions = _autoSetupOptionsOptions.Value.Tenants.FirstOrDefault(
                tenant => tenant.ShellName == _shellSettings.Name);
```

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Service/SetupWithRecipesFilterService.cs
> +            // the second case is when the tenant is already configured via AutoSetup feature.
Továbbra is 120 karakternél légyszi:
```suggestion
            // The first case is when specify the tenant recipe name via the Default tenant admin UI, the second case is
            // when the tenant is already configured via the AutoSetup feature.
```
És rakd fel ezt: https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2017andLater

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Service/SetupWithRecipesFilterService.cs
> +                    => hiddenCategories.Contains(category)));
```suggestion
                return recipesDescriptors
                    .Where(recipe => !recipe.Categories.Any(category => hiddenCategories.Contains(category)));
```

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Startup.cs
> +    public class AsdasdStartup : StartupBase
:(

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Startup.cs
> +    public class SetupStartup : StartupBase
Akkor legyen ugyanaz a neve, mint a feature-nek.

2021-10-20 20:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Manifest.cs
> +    DefaultTenantOnly = true,
Az Auto Setupnál (meg Setupnál) valahogy azt is megoldották, hogy ne lehessen bekapcsolni (mert ugye csak setup feauture), és akkor nem is kellene ez a beállítás:

![image](https://user-images.githubusercontent.com/1976647/138164437-81c6bb24-c6d5-48a0-92e0-9ffaf6538fd5.png)

2021-10-21 08:21 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +                        settings.HiddenCategories = new List<string>(categories)));
Nem szükséges

2021-10-21 08:25 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Service/SetupWithRecipesFilterService.cs
> +            // the second case is when the tenant is already configured via AutoSetup feature.
Ezt azért igy törtem mert követhetőbbnek gondoltam ha a két eset külön sorba kerül, de akkor kijavitom

2021-10-21 08:34 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Lombiq.Hosting.Tenants.Management.csproj
> +    <PackageReference Include="OrchardCore.AutoSetup" Version="1.0.0" />
Azért ez a package kellet mert a `AutoSetupOptions`-ra volt szükségem hogy ellenőrizhessem hogy az auto setup-nál vonatkozik e konfiguráció az adott tenantra de ezt megpróbálhatom megoldani másképpen.

2021-10-21 08:40 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Manifest.cs
> +    DefaultTenantOnly = true,
Igen ezen én is gondolkodtam hogy hogy lehet megoldani de mindenesetre most végére járok az ügynek

2021-10-21 09:16 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Lombiq.Hosting.Tenants.Management.csproj
> +    <PackageReference Include="OrchardCore.AutoSetup" Version="1.0.0" />
Mivel az `AutoSetup` is beálitja a `_shellSettings["RecipeName"]` ezért nem kell külön megnézni az `AutoSetupOptions`-t. Ezt a beálitást azonban a Default tenanton nem teszi meg furcsa módon de ezt elkerülhetjük azzal a defalut tenant nevére ellenőrzünk (`Services/SetupWithRecipesFilterService`):
```csharp
if (_shellSettings["RecipeName"] != null || currentTenantSetupOptions?.RecipeName != null)
```
helyett:
```csharp
if (_shellSettings["RecipeName"] != null || _shellSettings.Name.EqualsOrdinalIgnoreCase("Default"))
```

2021-10-21 10:20 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Manifest.cs
> +    DefaultTenantOnly = true,
Megtaláltam de sajnos nincs jó hirem. A setup és auto setup feature-nél azért nem látszik az enable mert a `OrchardCore.Features`-ben a feature listáért felelő cshtml-ben van egy ilyen sor:
 ```csharp
var showEnable = Model.IsAllowed(feature.Descriptor) && !missingDependencies.Any() && feature.Descriptor.Id != "OrchardCore.Setup" && feature.Descriptor.Id != "OrchardCore.AutoSetup";
```
Vagyis ezek be vannak égetve mint nem "bekapcsolható" modulok.

2021-10-21 10:32 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Manifest.cs
> +    DefaultTenantOnly = true,
A feature listát kiszolgáló viewmodelben van egy `Func`(fentebb: `IsAllowed`) ami eldönti hogy bekapcsolható e a modul. Ezt a controller a következőkppen definiálja:
```csharp
private bool FeatureIsAllowed(IFeatureInfo feature)
{
    // TODO: Implement white-list of modules allowed in the shell settings
    // Checks if the feature is only allowed on the Default tenant
    return _shellSettings.Name == ShellHelper.DefaultShellName || !feature.DefaultTenantOnly;
}
```
Tehát tűl nagy mozgás tér nincs arra hogy megmondjuk Mainfestből hogy egy feature bekapcsolható e. Foglalkozzunk ezzel a kérdés körrel vagy elég ha `DefaultTenantOnly = true`-val csak a default tenanton látsódik ez a kis "hiba"?

2021-10-21 10:56 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +        public static OrchardCoreBuilder HideRecipesByCategoryFromSetup(this OrchardCoreBuilder builder, params string[] categories) =>
Ha jól értem változtassam meg úgy a recipe-nek ne a `categories`-ját figyelje hanem a `tags`-et. Jelenleg a két meg nem jeleniteni kivánt recepeben a tag-ek: `dotnest `és `psiproctor`, az jó megvalósitás ha igy lehet majd megadni ezeket: 
```csharp
.HideRecipesByTagFromSetup("dotnest", "psiproctor");
```
Vagy legyen egy kinevezett tag(pl `hiddenOnSetupScreen `) és akkor a fenti függvény nem kap paramétert hanem ezt a tag-ot fogja keresni. Melyik legyen?

2021-10-21 14:08 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Lombiq.Hosting.Tenants.Management.csproj
> +    <PackageReference Include="OrchardCore.AutoSetup" Version="1.0.0" />
Szuper!

2021-10-21 14:09 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Manifest.cs
> +    DefaultTenantOnly = true,
Aha, hát ez elég béna. Akkor hagyjuk ezt ennyiben, viszont kérlek nyiss róla OC issue-t, hogy ez custom modulokból is megoldható legyen.

2021-10-21 14:11 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +        public static OrchardCoreBuilder HideRecipesByCategoryFromSetup(this OrchardCoreBuilder builder, params string[] categories) =>
Igen, úgy változtasd meg kérlek.

Az jó, ha továbbra is paraméterezhető ez a metódus megadott tag nevekkel, de lehet a default `"hiddenOnSetupScreen"` valóban. A mi recipe-inkben pedig állítsd be ezt a taget.

2021-10-25 18:38 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +        /// Registers Lombiq.Hosting.Tenants.Management.HideRecipesFromSetup as a setup feature and configure a set of
```suggestion
        /// Registers Lombiq.Hosting.Tenants.Management.HideRecipesFromSetup as a setup feature and configures a set of
```

2021-10-25 18:38 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +                        settings.HiddenTags = settings.HiddenTags.Concat(tags)));
Itt szerintem inkább felül kellene írni az optiont, és itt kezelni a defaultot (vagy az options classban). Szóval, hogy legyen lehetőséged a defaultot használni, teljesen mást használni, és a defaultot és mást is használni.

2021-10-25 18:38 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> -                        settings.HiddenCategories = new List<string>(categories)));
"Options" a class neve, szal a változónak is arra kellene utalnia.

2021-10-25 18:38 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Manifest.cs
> +    Description = "Ability to configure hostnames that don't allow during tenant creation.",
Kimaradt.

2021-10-25 18:51 UTC, Piedone requested changes

2021-10-25 18:51 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Manifest.cs
> +    Description = "Ability to configure recipe tags that won't be available during tenant setup.",
Talán így kicsit érthetőbb:
```suggestion
    Description = "Adds the ability to hide recipes from the setup screen based on configurable tags.",
```

2021-10-25 18:51 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Readme.md
> +**NOTE:** This extension method not only sets the tags you want to hide but also registers the feature as a setup feautre. If you just want to use the default hide tag you can call the extension func
Ezt inkább a method commentjébe kellene.

2021-10-25 18:51 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Settings/HideRecipesFromSetupOptions.cs
> +        public IEnumerable<string> HiddenTags { get; set; } = Array.Empty<string>();
```suggestion
        public IEnumerable<string> HiddenTags { get; set; } = Enumerable.Empty<string>();
```

2021-10-25 18:51 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Startup.cs
> +                settings => settings.HiddenTags = settings.HiddenTags.Concat(new[] { HiddenOnSetupScreen }));
```suggestion
                options => options.HiddenTags = options.HiddenTags.Concat(new[] { HiddenOnSetupScreen }));
```

2021-10-25 18:51 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Constants/DefaultValues.cs
> +        public const string HiddenOnSetupScreen = nameof(HiddenOnSetupScreen);
Itt hidden **on** setup screen van, máshol **from** setup screen. Melyik a helyes nyelvtan?

2021-10-25 18:51 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Service/SetupWithRecipesFilterService.cs
> +            // use auto setup.
Ez a "recepe" egy visszatérő becsípődés :).

```suggestion
            // The first case is when we specify the tenant recipe name via the Default tenant admin UI or AutoSetup
            // feature, the second case is necessary because the Default tenant doesn't fill in RecipeName even if we
            // use auto setup.
```

2021-10-25 18:51 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Service/SetupWithRecipesFilterService.cs
> +                    .Where(recipe => !recipe.Tags.Any(tag => hiddenTags.Contains(tag)));
```suggestion
                return recipesDescriptors.Where(recipe => !recipe.Tags.Any(tag => hiddenTags.Contains(tag)));
```

2021-10-28 16:30 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +                        settings.HiddenTags = settings.HiddenTags.Concat(tags)));
A defaultot átraktam a modelbe. Akkor az jó ha nem adunk meg paramétert akkor marad a default ha pedig megadunk paraméter(eke)t akkor felüliródik a lista a megadottakkal?

2021-10-28 16:33 UTC, Azaliusz commented on Lombiq.Hosting.Tenants.Management/Readme.md
> +**NOTE:** This extension method not only sets the tags you want to hide but also registers the feature as a setup feautre. If you just want to use the default hide tag you can call the extension func
Az jó ha a readmeben megtartom és a method kommentjét erre változtatom:
"Registers Lombiq.Hosting.Tenants.Management.HideRecipesFromSetup as a setup feature and configures a set of recipe tags that will be hidden on the setup screen. If you leave this method parameter empty then you can use the default, "HideFromSetupScreen" tag."

2021-10-28 16:54 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +                        settings.HiddenTags = settings.HiddenTags.Concat(tags)));
Igen.

2021-10-28 16:55 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Readme.md
> +**NOTE:** This extension method not only sets the tags you want to hide but also registers the feature as a setup feautre. If you just want to use the default hide tag you can call the extension func
Az első mondatot ennek mentén átírnám: https://github.com/Lombiq/Hosting-Tenants/pull/5#discussion_r735864302 A második mondat a paraméter docjába kellene.

2021-10-29 13:48 UTC, Piedone requested changes

2021-10-29 13:48 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Extensions/LombiqHostingTenantsManagementExtensions.cs
> +        /// use the default, "HideFromSetupScreen" tag.</param>
```suggestion
        /// <param name="tags">
        /// Recipe tags which will be hidden. If you leave this parameter empty then you can use the default,
        /// "HideFromSetupScreen" tag.
        /// </param>
```

2021-10-29 13:50 UTC, Piedone commented on Lombiq.Hosting.Tenants.Management/Readme.md
> +**NOTE:** This extension method not only sets the tags you want to hide but also registers the feature as a setup feautre. If you just want to use the default hide tag you can call the extension func
Ez a része kimaradt: "Az első mondatot ennek mentén átírnám: #5 (comment) "

2021-11-02 23:17 UTC, merged